<?php
/**
 * Admin seating version history page.
 * Lists generated seating-plan versions so previous outputs can be reviewed.
 */
session_start();

include 'includes/auth_check.php';
include 'includes/config.php';
require_once 'includes/security.php';

requireRole('admin', 'login.php');

include 'includes/header.php';
include 'includes/nav.php';

/* ================= SAFE QUERY ================= */
$result = $conn->query("
    SELECT *
    FROM seating_versions
    ORDER BY id DESC
");

/* stop if query fails */
if (!$result) {
    die("Database Error: " . $conn->error);
}
?>

<div class="bg-gray-100 min-h-screen py-10 px-4">

<div class="max-w-6xl mx-auto">

    <h1 class="text-3xl font-bold text-center text-emerald-700 mb-8">
        Seating Plan History
    </h1>

    <div class="bg-white shadow-xl rounded-xl overflow-hidden">

        <div class="overflow-x-auto p-4">

            <table class="min-w-full border border-gray-300">

                <thead class="bg-emerald-600 text-white">

                    <tr>
                        <th class="border px-4 py-3">ID</th>
                        <th class="border px-4 py-3">Version Name</th>
                        <th class="border px-4 py-3">Generated By</th>
                        <th class="border px-4 py-3">Generated At</th>
                        <th class="border px-4 py-3">Total Seats</th>
                        <th class="border px-4 py-3">Action</th>
                    </tr>

                </thead>

                <tbody>

                <?php if ($result->num_rows > 0): ?>

                    <?php while($row = $result->fetch_assoc()): ?>

                    <tr class="text-center">

                        <td class="border px-4 py-3">
                            <?= $row['id'] ?>
                        </td>

                        <td class="border px-4 py-3">
                            <?= htmlspecialchars($row['version_name']) ?>
                        </td>

                        <td class="border px-4 py-3">
                            <?= htmlspecialchars($row['generated_by']) ?>
                        </td>

                        <td class="border px-4 py-3">
                            <?= htmlspecialchars($row['generated_at']) ?>
                        </td>

                        <td class="border px-4 py-3">
                            <?= $row['total_entries'] ?>
                        </td>

                        <td class="border px-4 py-3">

                            <a href="view_seating_plan.php?version_id=<?= $row['id'] ?>&view=1"
                               class="bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded">

                                View

                            </a>

                        </td>

                    </tr>

                    <?php endwhile; ?>

                <?php else: ?>

                    <tr>
                        <td colspan="6" class="text-center py-6 text-red-500">
                            No seating plan versions found
                        </td>
                    </tr>

                <?php endif; ?>

                </tbody>

            </table>

        </div>

    </div>

</div>

</div>

<?php include 'includes/footer.php'; ?>
